### ISSUE TITLE
Disable shutdown countdown, shut down unconditionally

### ISSUE THREAD

**Issue by Ra72xx** [b-jesch/service.pvr.manager#1]
I'd like to be able to disable the shutdown timer. The powermanager service should offer the option to shut down Kodi unconditionally.

Reason:
I control my HTPC setup with a Harmony universal remote, and if I turn off everything with the remote, everything is supposed to shut down in accordance with Harmony's "activities" principle. Interfering by hand e.g. by cancelling the shutdown mixes this system up.

To make things worse, the Harmony seems to send additional IR signals to my HTPC, which are usually not interpreted by Kodi, but seem nevertheless to be interpreted by the PVR-Powermanager service as user activity. So every second or so shutdown is cancelled immediately without apparent reason (only unassigned keypresses in Kodi's log).

Alternatively it would help to assign a certain key (and not any activity) for the cancellation of the scheduled shutdown.

**Comment by b-jesch** [comment]
> Alternatively it would help to assign a certain key (and not any activity) for the cancellation of the scheduled shutdown.

I'll try to implement this in this way.

**Comment by Ra72xx** [comment]
Thanks! I currently just have somehow commented out the timeout part in the code.

**Comment by b-jesch** [comment]
Is it ok to use the select button (OK) for aborting the shutdown progress?

**Comment by Ra72xx** [comment]
Yes. The Harmony Hub seems to send signals interpreted as meaningless special key combinations (e.g. ctrl-shift) in addition to the poweroff, which nevertheless are interpreted as user activity by Kodi. So almost any real key should work :-) .
Thanks for the support!

**Comment by b-jesch** [comment]
Done. If you want to stay up to date, install my repository: [https://github.com/b-jesch/SaXBMC/raw/master/zip/repository.saxbmc/repository.saxbmc-1.0.1.zip](url)
